### ISSUE TITLE
secret key の場合は，Origin Header 設定に追加されていなくてもアクセスを許可してほしい

### ISSUE THREAD

**Issue by znppunfuv** [KEN-ALL/kenall-js#62]
ローカルの develop 環境においては secret key を使って開発しているのですが
secret key であっても，localhost を Origin Header に追加しないとアクセスできません

Origin Header に localhost を追加することは避けたいと考えています
なぜならば，public key は誰でも参照することが可能なものであり
誰かが localhost 環境を手元で立ち上げて，いたずらにクエリを叩いたことによるアカウント凍結やスパム認定のリスクがあるからです

## 実験したこと

| | Origin Header 設定あり | Origin Header 設定なし |
|:-:|:-:|:-:|
| public key | t | f |
| secret key | t | f |

## 環境

- @ken-all/kenall: 1.6.0
- 本番: public key を Parameter Store から env で流し込み && Kenall の Origin Header 設定にドメイン追加
- local: init.bash を実行し，`aws ssm get-parameters` で取ってきた secret key を .env.local に追加 && Kenall の Origin Header 設定にドメイン追加なし

**Comment by shiumachi** [comment]
ご要望ありがとうございます。

シークレットキーは、元々ダウンロードAPI等のサーバサイド専用APIで利用することを前提としたキーとして開発されたものでした。
なので、開発環境用の汎用キーとして使うことは想定しておりませんでした。
開発用のキーについては他のお客様からもご要望をいただいており、改善を検討しております。
今後のアップデートをお待ちいただきますよう、よろしくお願いいたします。

本リポジトリはクライアントライブラリのリポジトリのため、特に追加のコメント等なければ一旦クローズいたします。
ケンオール本体についてのご要望は[お問い合わせページ](https://kenall.jp/contact)よりご連絡いただけると大変助かりますので、ご協力をお願いいたします。

**Comment by moriyoshi** [comment]
お問い合わせの内容ですが、現時点ではスタンダードプラン以上のプランにご加入の場合、公開キーを複数発行できるようになっておりますので、お問い合わせの内容は実現できるものと考えます。この度はご要望をお寄せいただきありがとうございました。クローズとさせていただきます。
